config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sentences do
    resources :entities, only: [:new, :edit, :create, :update, :destroy]
  end

  root "sentences#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
# frozen_string_literal: true

class Entity < ApplicationRecord
  enum etype: { org: 0, gpe: 1, money: 2, theme: 3, time: 4 }

  belongs_to :sentence, touch: true

  validates :body, presence: true
end

app/models/sentence.rb
# frozen_string_literal: true

class Sentence < ApplicationRecord
  has_many :entities, dependent: :destroy

  validates :content, presence: true

  def words(except: false)
    result = content

    if except && with_entities?
      entities.pluck(:body).compact.each do |body|
        result.slice! body
      end
    end

    result.split(%r{[\s/,/-]}).reject(&:empty?).sort
  end

  def with_entities?
    entities.any?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/dry_controller.rb
# frozen_string_literal: true

module DryController
  extend ActiveSupport::Concern

  included do
    before_action :set_resource_class
    before_action :set_index, only: :index
    before_action :set_show, only: [:show, :edit, :update, :destroy]
  end

  def index
    @resource ||= resource_class.new
  end

  def show; end

  def new
    @resource = resource_class.new
  end

  def edit; end

  def create
    @resource = resource_class.new(resource_params)

    if @resource.save
      respond_to do |format|
        format.html do
          redirect_to "/" + controller_path,
            notice: I18n.t("views.common.created.success", name: resource_class.model_name.human)
        end
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @resource.update(resource_params)
      flash[:notice] = I18n.t("views.common.updated.success", name: resource_class.model_name.human)
      redirect_to(redirect_after_update)
    else
      flash[:error] = I18n.t("views.common.updated.error", name: resource_class.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @resource.destroy
      flash[:notice] = I18n.t("views.common.destroyed.success", name: resource_class.model_name.human)
      redirect_to("/" + controller_path)
    else
      flash[:error] = I18n.t("views.common.destroyed.error", name: resource_class.model_name.human)
      render(:edit)
    end
  end

  private

  def resource_class
    case controller_path.classify.downcase.to_s
    when "account"
      "User".constantize
    else
      controller_path.classify.constantize
    end
  end

  def set_index
    @resources = @resource_class.all
    # TODO: use pagy for pagination
    # @resources = @resource_class.all.page(params[:page])
    # @resources = @resources.unscope(:order).order("#{order} #{sort}") if params[:order].present?
  end

  def set_show
    @resource = resource_class.find(params[:id])
  end

  def set_resource_class
    @resource_class = resource_class
  end

  def redirect_after_update
    case controller_path.classify.downcase.to_s
    when "account"
      account_path(@resource)
    else
      "/" + controller_path
    end
  end
end

app/controllers/entities_controller.rb
# frozen_string_literal: true

class EntitiesController < ApplicationController
  before_action :set_sentence
  before_action :set_resource, only: [:edit, :update, :destroy]

  def new
    @resource = @sentence.entities.new
  end

  def create
    @resource = @sentence.entities.new(resource_params)
    @resource.body = params[:entity][:body].reject(&:empty?).join(" ")

    if @resource.save
      redirect_to new_sentence_entity_path([@sentence]), notice: I18n.t("views.common.created.success")
    end
  end

  def edit; end
  def update; end
  def destroy; end

  private

  def set_resource
    @resource = Entity.find(params[:id])
  end

  def set_sentence
    @sentence = Sentence.find(params[:sentence_id])
  end

  def resource_params
    accessible = [:body, :etype, :sentence_id]
    params.require(:entity).permit(accessible)
  end
end

app/controllers/sentences_controller.rb
# frozen_string_literal: true

class SentencesController < ApplicationController
  include DryController

  private

  def resource_params
    accessible = [:content, :pattern]
    params.require(:sentence).permit(accessible)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/entities_helper.rb
# frozen_string_literal: true

module EntitiesHelper
  def entity_formatted(entity)
    tag.span class: entity.etype.downcase.to_s do
      concat tag.span entity.body
      concat tag.span entity.etype, class: "etype"
    end
  end
end

app/helpers/sentences_helper.rb
# frozen_string_literal: true

module SentencesHelper
  def formatted_pattern(sentence)
    pattern = sentence.content

    sentence.entities.each do |entity|
      pattern.gsub!(entity.body, entity_formatted(entity))
    end

    pattern
  end
end

app/views/entities/new.html.erb
<div class="row mt-3">
  <div class="col-12 col-md-8 mx-auto mb-3">
    <%= tag.h3 "Manage entities for Sentence (# #{@sentence.id}):" %>
    <%= tag.h6 @sentence.content %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-12 col-md-8 mx-auto">
    <%= simple_form_for [@sentence, @resource] do |f| %>
      <% if @resource.errors.any? %>
        <div class="error-message">
          <%= @resource.errors.full_messages.to_sentence.capitalize %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-12 col-md-3 mb-3">
          <% if @sentence.with_entities? %>
            <h5>Entities available:</h5>
            <ul>
              <% @sentence.entities.each do |entity| %>
                <li class="mb-2"><%= entity_formatted(entity).html_safe %></li>
              <% end %>
            </ul>
          <% else %>
            <h5>No entities created yet</h5>
          <% end %>
        </div>
        <div class="col-12 col-md-4 mb-3">
          <%= f.input :body, label: "Select word(s):",
                              as: :check_boxes,
                              collection: @sentence.words(except: true), 
                              item_wrapper_class: "inline" %>
        </div>
        <div class="col-12 col-md-5 mb-3">
          <%= f.input :etype, as: :select,
                              label: "Define TYPE:", 
                              collection: Entity.etypes.map { |v,k| [v.upcase, v]},
                              prompt: "Select type for new Entity",
                              selected: "" %>
        </div>
      </div>
      <div class="row">
        <div id="actions" class="row mt-3">
          <div class="col-12 col-md-10 text-end">
            <%= link_to "Back to Sentences", sentences_path, class: "btn btn-sm btn-outline-dark" %>
            <%= f.submit "Save", class: "btn btn-sm btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sentence Entities App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/sentences/_form.html.erb
<%= simple_form_for @resource do |f| %>
  <% if @resource.errors.any? %>
    <div class="error-message">
      <%= @resource.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>
  <%= f.input :content, as: :text, wrapper_html: { class: "mb-3" } %>
  <div class="mb-3">
    <% if @resource.with_entities? %>
      <h5>Entities available:</h5>
      <ul>
        <% @resource.entities.each do |entity| %>
          <li class="mb-2"><%= entity_formatted(entity).html_safe %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div id="actions" class="row mt-3">
    <div class="col text-end">
      <%= link_to sanitize("&larr; Back to list"), sentences_path, class: "btn btn-sm btn-outline-dark" %>
      <%= f.submit "Save", class: "btn btn-sm btn-primary" %>
    </div>
  </div>
<% end %>

app/views/sentences/_resource.html.erb
<tr id="<%= dom_id(resource) %>">
  <th scope="row"><%= resource.id %></th>
  <td>
    <%= resource.with_entities? ? formatted_pattern(resource).html_safe : resource.content %>
  </td>
  <td><%= resource.entities.size %></td>
  <td class="text-end">
    <%= link_to "Manage entities", new_sentence_entity_path([resource]), class: "btn btn-sm btn-outline-primary" %>
    <%= link_to "Edit", edit_sentence_path(resource), class: "btn btn-sm btn-outline-warning" %>
  </td>
</tr>

app/views/sentences/create.turbo_stream.erb
<%= turbo_stream.append "sentences_list", partial: "sentences/resource", locals: { resource: @resource } %>
<%= turbo_stream.update Sentence.new, "" %>

app/views/sentences/edit.html.erb
<div class="row">
  <div class="col-12 col-md-6 mx-auto">
    <%= render "form" %>
  </div>
</div>

app/views/sentences/index.html.erb
<div class="row mt-3 mb-3">
  <div class="col-12 col-md-10 mx-auto text-end">
    <%= link_to "New sentence", new_sentence_path, class: "btn btn-sm btn-primary", data: { turbo_frame: dom_id(Sentence.new) } %>
  </div>
  <%= turbo_frame_tag Sentence.new %>
</div>
<div class="row">
  <div class="col col-md-10 mx-auto">
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Sentence</th>
          <th scope="col">Entities</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= turbo_frame_tag "sentences_list" do %>
          <% @resources.each do |resource| %>
            <%= render "resource", resource: resource  %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/sentences/new.html.erb
<%= turbo_frame_tag dom_id(@resource) do %>
  <div class="row mb-5">
    <div class="col col-md-10 mx-auto text-start">
      <h5>Add new sentence</h5>
    </div>
    <div class="col col-md-10 mx-auto">
      <%= render "form" %>
    </div>
  </div>
<% end %>

app/views/sentences/show.html.erb
<div class="row">
  <div class="col-8 mx-auto">
  </div>
</div>